services:
  db:
    container_name: devices-db
    image: postgres:17.7-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-device}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-devices} -h 0.0.0.0 -p 5432",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  statistics-api:
    build:
      context: ./statistics-api
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
    container_name: statistics-api
    command: ["sh", "-c", " yarn dev"]
    develop:
      watch: # Watch for changes in package.json to trigger deps rebuild
        - path: statistics-api/package.json
          action: rebuild
    ports:
      - "3000:3000"
    env_file: statistics-api/.env
    environment: # Override environment variables for docker compose services
      DB_HOST: db
      DEVICE_REGISTRATION_API: http://device-registration-api:3001
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes: # Mount source code for live development
      - ./statistics-api/src:/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  device-registration-api:
    build:
      context: ./device-registration-api
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
    container_name: device-registration-api
    command: ["sh", "-c", "yarn dev"]
    develop:
      watch: # Watch for changes in package.json to trigger deps rebuild
        - path: device-registration-api/package.json
          action: rebuild
    ports:
      - "3001:3001"
    env_file: device-registration-api/.env
    environment: # Override environment variables for docker compose services
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes: # Mount source code for live development
      - ./device-registration-api/src:/app/src
      - ./device-registration-api/migrations:/app/migrations
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
