services:
  db:
    container_name: device-db
    image: postgres:18.1-alpine
    environment:
      POSTGRES_PASSWORD: "99qKBHequrd6veHexXCa"
      POSTGRES_DB: device
      POSTGRES_USER: safra
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U safra -d device -h 0.0.0.0 -p 5432"]
      interval: 1s
      timeout: 1s
      retries: 600
