{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-deploy.fullname" . }}-config
  labels:
    {{- include "app-deploy.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
{{- end }}
