{{- if and .Values.openshift (.Capabilities.APIVersions.Has "route.openshift.io/v1") -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "app-deploy.fullname" . }}
  labels:
    {{- include "app-deploy.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "app-deploy.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
