{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-deploy.fullname" . }}-secrets
  labels:
    {{- include "app-deploy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
