apiVersion: v1
kind: ConfigMap
metadata:
  name: device-registration-api-config
  labels:
    {{- include "device-registration-api.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
